[package]
name = "kohebi-capi"
description = "CPython C-API emulation implemented in Rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["python", "runtime", "interpreter", "compiler", "kohebi"]
categories = ["compilers", "development-tools"]

[lints]
workspace = true

[dependencies]
kohebi-core.workspace = true
kohebi-abi.workspace = true
