[package]
name = "kohebi-parse"
description = "Lexer, parser, and CPython-compatible AST for kohebi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
kohebi-core.workspace = true
unicode-ident.workspace = true
memchr.workspace = true
smallvec.workspace = true
thiserror.workspace = true
