#!/usr/bin/env python3
"""Generate the Unicode tables the `is` methods on `str` need.

Twelve methods asking eleven different questions, and the names do not tell you
which. `isdigit`, `isdecimal` and `isnumeric` sound like one question asked
three ways and are three properties that nest: `'٣'` is all three, `'³'` is the
last two, `'½'` is only the last. `isalpha` is `Alphabetic` and not the letter
categories. `isspace` counts four separators Unicode does not call whitespace.
`isidentifier` is `XID_Start` and `XID_Continue` and knows nothing about
keywords, so `'if'.isidentifier()` is true.

Like `tools/gen-case.py`, everything is read off the CPython being matched
rather than out of a copy of the Unicode data files, and read off the method
itself where there is one. `isalpha` on a one character string is the
`Alphabetic` property with nothing in the way, so that is the probe.

Three of the eleven are not here. `isprintable` is already a table, in
`printable.rs`. `islower`, `isupper` and `istitle` are case questions and their
data is in `casing`. `isascii` is a comparison.

Run this against the CPython whose output we are matching, and check the result
in.

    python3 tools/gen-classify.py
    cargo fmt
"""

from __future__ import annotations

import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "crates/kohebi-core/src/classify/table.rs"
LAST = 0x110000
PER_LINE = 4


def points() -> list[int]:
    """Every code point except the surrogates."""
    return [cp for cp in range(LAST) if not 0xD800 <= cp <= 0xDFFF]


def runs(holds) -> list[tuple[int, int]]:
    """The code points the predicate holds for, collapsed into ranges."""
    out: list[list[int]] = []
    for cp in points():
        if not holds(cp):
            continue
        if out and out[-1][1] + 1 == cp:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return [(lo, hi) for lo, hi in out]


def hex_literal(cp: int) -> str:
    """A hex literal in the shape the lint wants for its width."""
    if cp <= 0xFFFF:
        return f"0x{cp:04X}"
    return f"0x{cp >> 16:04X}_{cp & 0xFFFF:04X}"


def ranges_of(name: str, what: str, table: list[tuple[int, int]]) -> str:
    body = "".join(
        "    " + " ".join(f"({hex_literal(lo)}, {hex_literal(hi)})," for lo, hi in table[at : at + PER_LINE]) + "\n"
        for at in range(0, len(table), PER_LINE)
    )
    return f"""
/// {what}
pub(super) static {name}: [(u32, u32); {len(table)}] = [
{body}];
"""


def main() -> int:
    parts = [
        f"""//! Unicode classification data, generated from {unicodedata.unidata_version}.
//!
//! Generated by `tools/gen-classify.py`. Do not edit.
//!
//! Rust has an answer of its own for some of these and it is not the same
//! answer. `char::is_whitespace` leaves out the four separators Python counts,
//! `char::is_numeric` is the widest of the three number properties rather than
//! any particular one of them, and there is no `XID_Start` at all. The tables
//! are read off CPython for the same reason the case ones are, which is that
//! they should move when this file is regenerated and not when the compiler
//! updates its own copy of the data.
""",
        ranges_of(
            "ALPHABETIC",
            "`isalpha`, which is the `Alphabetic` property and so is wider than\n/// the letter categories: a Hangul syllable and a roman numeral are both in.",
            runs(lambda cp: chr(cp).isalpha()),
        ),
        ranges_of(
            "DECIMAL",
            "`isdecimal`, the narrowest of the three, being what a positional\n/// system is written with. `int()` accepts exactly these.",
            runs(lambda cp: chr(cp).isdecimal()),
        ),
        ranges_of(
            "DIGIT",
            "`isdigit`, which is [`DECIMAL`] and the ones that are a digit\n/// without being usable in a number, such as the superscripts.",
            runs(lambda cp: chr(cp).isdigit()),
        ),
        ranges_of(
            "NUMERIC",
            "`isnumeric`, which is [`DIGIT`] and everything else that carries a\n/// numeric value, such as the fractions and the roman numerals.",
            runs(lambda cp: chr(cp).isnumeric()),
        ),
        ranges_of(
            "SPACE",
            "`isspace`, which is Unicode's whitespace and the four file, group,\n/// record and unit separators, which Unicode does not call whitespace.",
            runs(lambda cp: chr(cp).isspace()),
        ),
        ranges_of(
            "XID_START",
            "What a name may begin with, which includes the underscore because\n/// `isidentifier` asks about a Python name rather than about the property.",
            runs(lambda cp: chr(cp).isidentifier()),
        ),
        ranges_of(
            "XID_CONTINUE",
            "What a name may carry on with, probed by putting the code point\n/// after one that is known to start a name.",
            runs(lambda cp: ("a" + chr(cp)).isidentifier()),
        ),
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
