#!/usr/bin/env python3
"""Generate the single byte codec tables a source encoding declaration can name.

PEP 263 lets a file say what encoding it is written in, and the name it gives
is looked up in CPython's whole codec registry. Most of that registry is
charmap codecs: 256 bytes, one code point each, and nothing else to know. Those
are a table rather than an algorithm, so they are generated from the CPython we
are matching rather than written out by hand.

Three things come out of here. The tables themselves, the alias table that
turns `latin1` and `8859` and `L1` into the same codec, and the list of every
codec module CPython ships, which is what lets us tell a name we have not
implemented apart from a name that does not exist.

    python3 tools/gen-charmap.py > crates/kohebi-parse/src/source/charmap.rs
    cargo fmt

Re-run it when we move to a newer CPython.
"""

from __future__ import annotations

import encodings
import encodings.aliases
import importlib
import pkgutil
import sys

UNDEFINED = 0xFFFF
PER_LINE = 8


def modules() -> list[str]:
    """Every codec module in the `encodings` package, sorted.

    `aliases` lives in there and is not a codec, so a module has to offer
    `getregentry` to count. `mbcs` and `oem` are the exception: they are codecs
    and they only import on Windows, so an `ImportError` keeps the name rather
    than dropping it. That is deliberate. A file that asks for `mbcs` is asking
    for something real, and telling the user we have not implemented it is
    closer to the truth than telling them it does not exist.
    """
    out = []
    for found in pkgutil.iter_modules(encodings.__path__):
        try:
            module = importlib.import_module("encodings." + found.name)
        except ImportError:
            out.append(found.name)
            continue
        if hasattr(module, "getregentry"):
            out.append(found.name)
    return sorted(out)


def charmaps() -> list[tuple[str, list[int], bool]]:
    """The name, the 256 code points, and whether the low half is ASCII.

    `ascii` and `latin_1` are written in C and have no `decoding_table`, so
    they are built here from what they are defined to be. Everything else is a
    charmap module and hands its table over directly.
    """
    out: list[tuple[str, list[int], bool]] = [
        ("ascii", [cp if cp < 0x80 else UNDEFINED for cp in range(256)], True),
        ("latin_1", list(range(256)), True),
    ]
    for name in modules():
        try:
            module = importlib.import_module("encodings." + name)
        except ImportError:
            continue
        table = getattr(module, "decoding_table", None)
        if table is None or len(table) != 256:
            continue
        points = [UNDEFINED if ch == "￾" else ord(ch) for ch in table]
        out.append((name, points, points[:0x80] == list(range(0x80))))
    out.sort()
    return out


def check(name: str, points: list[int]) -> None:
    """The table is `u16`, so nothing in it may need more than 16 bits.

    A code point of exactly U+FFFF would collide with the sentinel. No codec
    has one, because U+FFFF is a noncharacter, and this is here so that we find
    out rather than corrupt a table if that ever stops being true.
    """
    for byte, cp in enumerate(points):
        if cp == UNDEFINED:
            continue
        if cp >= 0xFFFF or 0xD800 <= cp <= 0xDFFF:
            sys.exit(f"{name}: byte {byte:#04x} maps to U+{cp:04X}, which the table cannot hold")


def table(points: list[int]) -> str:
    lines = []
    for start in range(0, 256, PER_LINE):
        row = points[start : start + PER_LINE]
        lines.append("    " + " ".join(f"0x{cp:04X}," for cp in row))
    return "\n".join(lines)


def main() -> None:
    maps = charmaps()
    for name, points, _ in maps:
        check(name, points)

    # An alias is only worth carrying if it names a codec that exists, which
    # every one of them does, but the check is free and the list is CPython's.
    known = set(modules())
    aliases = sorted(
        (alias, target)
        for alias, target in encodings.aliases.aliases.items()
        if target in known
    )

    out = sys.stdout.write
    out(
        f"""//! The single byte codecs a source encoding declaration can name.
//!
//! Generated by `tools/gen-charmap.py` from CPython {sys.version.split()[0]}. Do not edit.
//!
//! A charmap codec is 256 code points and no rules, so it is a table. There
//! are {len(maps)} of them, which is most of what PEP 263 can name and all of
//! what any real file names. The multi byte codecs, which are the CJK ones and
//! the stateful ISO 2022 family, are not here and are refused by name.

/// One byte codec: what each of the 256 byte values means.
#[derive(Debug)]
pub struct Charmap {{
    /// The module name in CPython's `encodings` package, underscores and all.
    pub name: &'static str,
    /// `UNDEFINED` where the byte has no meaning and decoding fails.
    pub table: &'static [u16; 256],
    /// Whether bytes 0x00 to 0x7F stand for themselves.
    ///
    /// True for all but the EBCDIC codecs, and what lets a file of plain ASCII
    /// skip the table and the reallocation both.
    pub ascii: bool,
}}

/// The byte has no meaning in this codec.
///
/// U+FFFF is a noncharacter and no codec maps to it, which is what makes it
/// usable as the hole in a `u16` table. The generator checks that.
pub const UNDEFINED: u16 = 0xFFFF;

"""
    )

    for name, points, _ in maps:
        out(f"static {name.upper()}: [u16; 256] = [\n{table(points)}\n];\n\n")

    out(f"/// Every charmap codec, sorted by name so a lookup can bisect.\npub static CHARMAPS: [Charmap; {len(maps)}] = [\n")
    for name, _, ascii_low in maps:
        out(
            f'    Charmap {{ name: "{name}", table: &{name.upper()}, '
            f"ascii: {str(ascii_low).lower()} }},\n"
        )
    out("];\n\n")

    out(
        f"""/// `encodings.aliases.aliases`, sorted by alias.
///
/// The spelling a file uses is almost never the module name. `latin-1`,
/// `8859`, `cp819`, and `L1` all mean `iso8859_1`, and this is the table that
/// says so.
pub static ALIASES: [(&str, &str); {len(aliases)}] = [
"""
    )
    for alias, target in aliases:
        out(f'    ("{alias}", "{target}"),\n')
    out("];\n\n")

    names = sorted(known)
    out(
        f"""/// Every codec module CPython ships, sorted.
///
/// A name in here that is not in `CHARMAPS` is one we have not implemented,
/// and a name in neither does not exist. Those are different failures and a
/// user is owed the difference.
pub static CODECS: [&str; {len(names)}] = [
"""
    )
    for name in names:
        out(f'    "{name}",\n')
    out("];\n")


if __name__ == "__main__":
    main()
