#!/usr/bin/env python3
"""Generate the table of code points Python does not print literally in a repr.

`repr` on a string escapes anything `str.isprintable` calls unprintable, so
matching CPython's output means knowing exactly which code points those are.
That is the Unicode general category of every code point in the standard, which
is 1.1 million answers and not something to hand-write or to guess at.

Run this against the CPython whose output we are matching, and check the result
in. Re-run it when we move to a Python built on a newer Unicode.

    python3 tools/gen-printable.py > crates/kohebi-parse/src/printable.rs
    cargo fmt
"""

from __future__ import annotations

import sys
import unicodedata

PER_LINE = 4


def ranges() -> list[tuple[int, int]]:
    """Every run of code points that `str.isprintable` refuses, merged."""
    out: list[tuple[int, int]] = []
    start: int | None = None
    for cp in range(0x110000):
        if chr(cp).isprintable():
            if start is not None:
                out.append((start, cp - 1))
                start = None
        elif start is None:
            start = cp
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def hex_literal(cp: int) -> str:
    """A hex literal clippy will not ask for underscores in."""
    if cp <= 0xFFFF:
        return f"0x{cp:04X}"
    return f"0x{cp >> 16:04X}_{cp & 0xFFFF:04X}"


def main() -> int:
    table = ranges()
    # Everything below U+0080 is decided without the table, so the entries for
    # it would never be read. They stay in anyway: a table that covers the whole
    # range can be checked against `str.isprintable` code point by code point,
    # and one with a hole in it cannot.
    write = sys.stdout.write
    write(f"""\
//! Which code points `repr` prints literally, generated from Unicode {unicodedata.unidata_version}.
//!
//! Generated by `tools/gen-printable.py`. Do not edit.
//!
//! CPython escapes any character `str.isprintable` refuses, which is anything
//! in general category Cc, Cf, Cs, Co, Cn, Zl, Zp, or Zs, with the single
//! exception of the space at U+0020. Matching its `repr` output means agreeing
//! with that judgement on all {0x110000} code points, so the answer is a table
//! rather than a rule.

/// Runs of code points that are not printable, sorted and non-overlapping.
static UNPRINTABLE: [(u32, u32); {len(table)}] = [
""")
    for i in range(0, len(table), PER_LINE):
        chunk = table[i : i + PER_LINE]
        write("    " + " ".join(f"({hex_literal(lo)}, {hex_literal(hi)})," for lo, hi in chunk) + "\n")
    write("""];

/// Whether `c` is printed as itself by `repr`, rather than as an escape.
///
/// Agrees with `str.isprintable` on every code point, which the tests check
/// against a fixture generated from CPython rather than by reimplementing the
/// same rule twice and comparing it with itself.
#[must_use]
pub fn is_printable(c: char) -> bool {
    let cp = c as u32;
    // ASCII is most of every real file, and it is one comparison rather than a
    // binary search over seven hundred ranges.
    if cp < 0x80 {
        return (0x20..0x7F).contains(&cp);
    }
    UNPRINTABLE
        .binary_search_by(|&(lo, hi)| {
            if cp < lo {
                std::cmp::Ordering::Greater
            } else if cp > hi {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_err()
}
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
